services:
  mysql:
    image: mysql:8
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: Test.123
      MYSQL_DATABASE: filesystem
    networks:
      - app-network
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount init.sql here
    restart: always

  # fuse-container:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: fuse-container
  #   environment:
  #     - MYSQL_HOST=mysql8
  #     - MYSQL_PORT=3306
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=Test.123
  #     - MYSQL_DATABASE=filesystem
  #   networks:
  #     - app-network
  #   depends_on:
  #     - mysql
  #   volumes:
  #     - ./fuse-data/:/app/
  #     # - /mnt/virtual_fs/:/mnt/virtual_fs/
  #   cap_add:
  #     - SYS_ADMIN
  #   devices:
  #     - /dev/fuse
  #   security_opt:
  #     - apparmor:unconfined
  #   privileged: true

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  # fuse-data:
  #   driver: local
